
services:
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - mysql-compose-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_ROOT_DATABASE=rootdb
    ports:
      - "3307:3306"

volumes:
  mysql-compose-volume: